
server:
  port: 8080
  #servlet:
    #context-path: /myblog

# ===============================thymeleaf==============================================
thymeleaf:
  # HTML5标准
  mode: HTML5

# =============================spring================================================

spring:
  #数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: a8899543
    url: jdbc:mysql://www.czh2you.com:3306/MyBlog?useUnicode=true&characterEncoding=utf-8&useSSL=false

  # elasticsearch
  data:
    elasticsearch:
      cluster-name: MyBlogEs
      cluster-nodes: www.czh2you.com:9300

    properties:
      transport:
        tcp:
          connect_timeout: 1200s   # 设置连接超时时间

  #redis
  redis:
    host: www.czh2you.com
    lettuce:
      pool:
        max-active: 8
        max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8  # 连接池中的最大空闲连接 默认 8
        min-idle: 1   # 连接池中的最小空闲连接 默认 1
    timeout: 60s



  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect #设置方言


# ==================================mybatis=======================================
mybatis:
  #config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml


  #configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl    #打印sql语句


# ==================================logging=======================================

  #level:
    #root: info       #根目录是信息级别
    #com.myblog.dao: debug    #dao层是debug级别





