
server:
  port: 8081
  #servlet:
    #context-path: /myblog

# ===============================thymeleaf==============================================

thymeleaf:
  # 热部署静态文件
  cache: false
  # HTML5标准
  mode: HTML5

# =============================spring================================================

spring:
  #数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:  123456
    url: jdbc:mysql://localhost:3306/MyBlog?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC


  # elasticsearch
  data:
    elasticsearch:
      cluster-name: master
      cluster-nodes:localhost:9300

  #redis
  redis:
    host: localhost
    lettuce:
      pool:
        max-active: 8
        max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8  # 连接池中的最大空闲连接 默认 8
        min-idle: 1   # 连接池中的最小空闲连接 默认 1
    timeout: 60s

  #设置开启热部署
  devtools:
    restart:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

# ==================================mybatis=======================================
mybatis:
  #config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml


  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl    #打印sql语句




